### ISSUE TITLE
RFC: Deprecating `sync`

### ISSUE THREAD

**Issue by yumauri** [yumauri/effector-storage#14]
Is `sync` flag is needed?

I've marked it as **deprecated**, because I thought there is no any need to have non-synced browser tabs.
But as of today there is at least one request to keep this option.

Maybe rename it with something else? To eliminate confusion with synchronizing stores, persisted with the same key.

**Comment by ilyaagarkov** [comment]
I have a use case for this flag

I don't need to sync some value between tabs in runtime but I need to save the last selected value to ls

Example: Calendar with 3  types of view(month/week/day) I wanna save last selected type to ls. But if user has 2 tabs with the calendar I don't want to switch view type for one tab on selecting view type in another one

**Comment by yumauri** [comment]
Due to several actual use cases in the wild (one of them in the comment above), I decided to **leave** this option.

I’ve removed deprecation note from documentation and from the source code.

_Any suggestions about better naming are appreciated though, but I’ll close this issue for now._
