### ISSUE TITLE
Error on node 12

### ISSUE THREAD

**Issue by eonprojetos** [yumauri/effector-storage#16]
Hi!
I'm using effector and effector-storage on a NextJS project with node 10, and everything was working fine. But updating to node 12 today got this error message, on build:

> 03:48:26.770 | > Build error occurred
03:48:26.772 | Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /vercel/workpath0/node_modules/effector-storage/session/index.cjs.js
03:48:26.772 | require() of ES modules is not supported.
03:48:26.772 | require() of /vercel/workpath0/node_modules/effector-storage/session/index.cjs.js from /vercel/workpath0/.next/serverless/pages/simulador/contrate.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
03:48:26.772 | Instead rename index.cjs.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /vercel/workpath0/node_modules/effector-storage/session/package.json.
03:48:26.772 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
03:48:26.772 | at Module.load (internal/modules/cjs/loader.js:863:32)
03:48:26.772 | at Function.Module._load (internal/modules/cjs/loader.js:708:14)
03:48:26.772 | at Module.require (internal/modules/cjs/loader.js:887:19)
03:48:26.772 | at require (internal/modules/cjs/helpers.js:74:18)
03:48:26.772 | at Object.4F12 (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:223:18)
03:48:26.772 | at __webpack_require__ (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:23:31)
03:48:26.773 | at Object.6iff (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:264:82)
03:48:26.773 | at __webpack_require__ (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:23:31)
03:48:26.773 | at Module.hcvy (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:3209:17)
03:48:26.773 | at __webpack_require__ (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:23:31)
03:48:26.773 | at Module.PdgD (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:504:21)
03:48:26.773 | at __webpack_require__ (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:23:31)
03:48:26.773 | at /vercel/workpath0/.next/serverless/pages/simulador/contrate.js:91:18
03:48:26.773 | at Object.<anonymous> (/vercel/workpath0/.next/serverless/pages/simulador/contrate.js:94:10)
03:48:26.773 | at Module._compile (internal/modules/cjs/loader.js:999:30) {
03:48:26.773 | code: 'ERR_REQUIRE_ESM'
03:48:26.773 | }
03:48:26.805 | error Command failed with exit code 1.
03:48:26.805 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
03:48:26.818 | Error: Command "yarn run build" exited with 1
03:48:29.474 | Done with "package.json"

**Comment by yumauri** [comment]
Hello!

I'm not familiar with NextJS, unfortunately, could that be an issue with NextJS itself? Like in this issue — https://github.com/sindresorhus/ky/issues/322, or this — https://github.com/vercel/next.js/issues/9607

Also, can you try to downgrade effector-storage version to **4.0.2**? Just to check, if this will work. There weren't any major changes between 4.0.2 and latest 4.1.1, but in version 4.0.3 I've renamed `.cjs` files to `.cjs.js`, to support [FuseBox 3](https://fuse-box.org/). Maybe `.cjs` files will work fine in your setup?

**Comment by eonprojetos** [comment]
Hi!

Downgrading the version seens to work fine with Node 12!

For the possible problem with NextJS, I'm going to try other versions to see if anything changes.


Many thanks for the fast reply!

**Comment by yumauri** [comment]
If downgrading version to 4.0.2 works fine, I'll consider changing extension back to `.cjs` for Common JS modules...
Or maybe second way — is to remove `"type": "module"` from `package.json` and changing extension to `.mjs` for ES modules.
I'll try different approaches in a few days (hopefully).

**Comment by zerobias** [comment]
I'm suggesting to remove `type` field from `package.json`, it's not necessary with precisely described `exports` field like ours

**Comment by yumauri** [comment]
Sorry for long delay...

I've decided to change extension for CommonJS modules back to `.cjs`, like it was in version 4.0.2.
Mainly because package [dual-publish](https://github.com/ai/dual-publish) makes this way. So, any package, released with dual-publish, will not work with FuseBox3.
Also, guys from FuseBox team are suggesting to use version 4 themselves in the issue [#1383](https://github.com/fuse-box/fuse-box/issues/1383). Latest FuseBox 3.7.1 was released two years ago, I hope no one uses it anymore :)

I don't want to remove `type` field from `package.json` because I think we need to move forward, from CommonJS to ESM :) Till the end of this year Sindre Sorhus [intends to move most of his packages to pure ESM](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77), I hope this will be a huge impact to the all maintainers.

@eonprojetos You can grab latest version 4.2.0 — I've checked it with NextJS + Node 12.20.2, and build is working fine.
