### ISSUE TITLE
Add adapter key prefix

### ISSUE THREAD

**Issue by yumauri** [yumauri/effector-storage#28]
Let's say you have two separate applications on the same domain

- https://domain/app1/
- https://domain/app2/

As long as they are located on the same domain — they shares same local storage space. And this can lead to keys conflicts. For example, both applications has store `$isAuthenticated` and both applications persists this store with the key `authenticated` in storage.

It could be hard to maintain unique keys manually, so, idea is to add possibility to specify global (per adapter) key prefix. For example:

```javascript
import { createStore } from 'effector'
import { persist, configure } from 'effector-storage/local'

configure({
  keyPrefix: 'app1/'
})

const $isAuthenticated = createStore(false)
persist({
  store: $isAuthenticated,
  key: 'authenticated' // <- actual localStorage key will be "app1/authenticated"
})
```

(This API example is just an idea and subject to change)

**Comment by AlexandrHoroshih** [comment]
The global configuration tricks look very suspicious to me

Maybe something like this?
```ts
const prefix = detectAppPrefix();

const appPersist = createPersist({
 keyPrefix: prefix,
 // option to add more configuration options in the future, if needed
})

const $isAuthenticated = createStore(false)
appPersist({
  store: $isAuthenticated,
  key: 'authenticated' // <- actual localStorage key will be "app1/authenticated"
})
```

**Comment by yumauri** [comment]
Hm, I agree, this looks more robust.

But it is always irritates me in `ky` that if I want to change some options globally — I need to create separate instance of `ky` and use it everywhere across the application...

What about both ways?
For example `axios` supports changing global defaults _and_ creating separate instance with its own defaults:
https://github.com/axios/axios#config-defaults

**Comment by yumauri** [comment]
Taking `axios` behaviour as an example:

Global configuration:
```javascript
persist.defaults.keyPrefix = 'app/'

const $isAuthenticated = createStore(false)
persist({
  store: $isAuthenticated,
  key: 'authenticated' // <- actual localStorage key will be "app/authenticated"
})
```

Instance configuration:
```javascript
const appPersist = persist.create({
  keyPrefix: 'app/',
})

const $isAuthenticated = createStore(false)
appPersist({
  store: $isAuthenticated,
  key: 'authenticated' // <- actual localStorage key will be "app/authenticated"
})

// defaults can be changed on instance as well
appPersist.defaults.keyPrefix = 'app2/'
```

**Comment by AlexandrHoroshih** [comment]
I don't know, i really don't like global configration hooks 
🤷

What is correct behavior, if user changed global configuration long after all persists are set? or if global configuration changes on the fly?

Maybe forbid to change configuration if there are persisted stores already, or allow to call this `configure` function only one time? 🤔

**Comment by yumauri** [comment]
After several days of thinking I have come to conclusion, that you are right — global configuration will add useless complexity and strange behaviour.

Added `createPersist` factory in [version 4.4.0](https://github.com/yumauri/effector-storage/releases/tag/v4.4.0).
