### ISSUE TITLE
incorrect operation of the store

### ISSUE THREAD

**Issue by mg901** [yumauri/effector-storage#5]
When the page is reloaded, slashes get to the side.

**Comment by yumauri** [comment]
Can you, please, provide more information?
Test project would be great.

I tried this code:

```javascript
import { createStore } from 'effector'
import withStorage from 'effector-storage'

const createStorageStore = withStorage(createStore)

const store = createStorageStore(null, { key: 'store' })
store.watch(_ => console.log('store:', _))
```

And cannot reproduce:
![effector-storage](https://user-images.githubusercontent.com/6583994/83551866-97524600-a511-11ea-9802-99e2007b3572.gif)
