### ISSUE TITLE
Update effector peer dependency

### ISSUE THREAD

**Issue by yumauri** [yumauri/effector-storage#6]
![image](https://user-images.githubusercontent.com/6583994/87420431-ed6cdb80-c5dd-11ea-97c2-3b35baf472ee.png)

**Comment by victordidenko** [comment]
Fixed in [this commit](https://github.com/yumauri/effector-storage/commit/09063fe9e608db7b6b632b42ab03320411f61cda) and published in [version 3.0.0](https://github.com/yumauri/effector-storage/releases/tag/v3.0.0)
