### ISSUE TITLE
Add automated dependency updates

### ISSUE THREAD

**Issue by yumauri** [yumauri/effector-storage#8]
dependabot? greenkeeper?
https://github.com/marketplace/category/dependency-management

**Comment by NikitaIT** [comment]
just set effector in devDependencies, not a peerDependencies, you do not really depend on the effector code, only on types, so you can create an interface and just check what the effector can be passed to this interface

**Comment by yumauri** [comment]
There are other dependencies, used prior to building, this issue is related to them, actually, not just to `effector`:
```
  "devDependencies": {
    "@size-limit/preset-small-lib": "^4.5.4",
    "@types/jest": "^26.0.4",
    "@types/node": "^14.0.23",
    "dual-publish": "^0.11.0",
    "effector": "^21.0.3",
    "jest": "^26.1.0",
    "np": "^6.3.2",
    "prettier": "^2.0.5",
    "size-limit": "^4.5.4",
    "ts-jest": "^26.1.2",
    "tslint": "^6.1.2",
    "tslint-config-prettier": "^1.18.0",
    "tslint-config-security": "^1.16.0",
    "tslint-config-standard-plus": "^2.3.0",
    "typescript": "^3.9.6"
  },
```

**Comment by yumauri** [comment]
I've added config for Renovate, let's check, how this will come out
https://github.com/yumauri/effector-storage/commit/1eb90c01a9e2564490749c3e799b9bf6be4ea93e

**Comment by yumauri** [comment]
Looks like Renovate works fine now
https://github.com/yumauri/effector-storage/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Frenovate
So I'll close this issue finally :)
